/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "lae43d"
include("lesson08-reflect:reflect-java")
include("lesson09-reflect-kotlin")
include("lesson10-annotations")
include("lesson13&14-JMH-microbench-mapper")
include("lesson15-bytecode")
include("lesson16-class-file-api")
include("lesson17-dynamic-mapper")
